# Generated by Django 2.2 on 2021-11-30 21:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 30, 21, 31, 28, 154090, tzinfo=utc), editable=False),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 30, 21, 31, 28, 154113, tzinfo=utc)),
        ),
    ]
