# Generated by Django 2.2 on 2021-11-30 21:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211130_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 30, 21, 35, 39, 998807, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 30, 21, 35, 39, 998829, tzinfo=utc)),
        ),
    ]
