# Generated by Django 2.2 on 2022-01-11 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blogpost_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='writer',
            new_name='author',
        ),
    ]
