# Generated by Django 2.2 on 2021-11-30 21:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211130_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='modified',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 30, 21, 35, 52, 638945, tzinfo=utc), editable=False),
        ),
    ]
