# Generated by Django 2.2 on 2021-11-30 21:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20211130_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 30, 21, 36, 2, 74066, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 30, 21, 36, 2, 74036, tzinfo=utc), editable=False),
        ),
    ]
