# Generated by Django 2.2 on 2021-11-30 21:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211130_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
