# Generated by Django 2.2 on 2021-11-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20211130_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
